sudo: false

env:
  global:
  - CHART_TESTING_TAG="v1.0.3"
  - TEST_IMAGE_TAG="v2.0.3"
  - CHARTS_REPO="https://github.com/rimusz/charts-testing-travisci"
  - TRAVISCI_RUN="true"

before_script:
# Decrypt the credentials
- openssl aes-256-cbc -K $encrypted_b335e931294b_key -iv $encrypted_b335e931294b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz

script:
- echo "Run linting charts-testing linting"
- ./test/lint_charts.sh || travis_terminate 1
- echo "Run full charts-testing on GKE"
- ./test/e2e_gke.sh || travis_terminate 1

notifications:
  email: false
