sudo: false

env:
  global:
  - CHART_TESTING_VERSION="v1.0.3"
  - TEST_IMAGE_TAG="v2.0.3"
  - CHARTS_REPO="https://github.com/rimusz/charts-testing-travisci"

before_install:
# Decrypt the credentials
- openssl aes-256-cbc -K $encrypted_b335e931294b_key -iv $encrypted_b335e931294b_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz

before_script:
- docker pull gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} || travis_terminate 1
- echo "Run local charts-testing with linting only"
- docker run --rm -e CHART_DIRS="stable" -v "$(pwd):/workdir" --workdir /workdir gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} chart_test.sh --no-install || travis_terminate 1

script:
- echo "Run charts-testing with install only on GKE"
- ./.scripts/run_e2e_gke.sh

notifications:
  email: false
