#sudo: required

env:
  global:
    - CHART_TESTING_VERSION="v1.0.3"
    - HELM_VERSION="v2.9.1"

# Some initial setup
before_install:
- sudo apt-get update
- sudo apt-get install -y socat util-linux

# Copy nsenter tool for Ubuntu 14.04 (current travisCI build VM version)
- sudo docker run --rm -v $(pwd):/target jpetazzo/nsenter
- sudo mv -fv nsenter /usr/local/bin/

script:
# Run charts-testing linting
- docker run --rm -e CHART_DIRS="stable" -v "$(pwd):/workdir" --workdir /workdir gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} chart_test.sh --no-install

notifications:
  email: false
