sudo: required

env:
  global:
    - K8S_VERSION="v1.10.6"
    - CHART_TESTING_VERSION="v1.0.3"
    - HELM_VERSION="v2.9.1"

# Some initial setup
before_install:
- sudo apt-get update
- sudo apt-get install -y socat util-linux

# Copy nsenter tool for Ubuntu 14.04 (current travisCI build VM version)
- sudo docker run --rm -v $(pwd):/target jpetazzo/nsenter
- sudo mv -fv nsenter /usr/local/bin/

before_script:
- docker pull gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} || travis_terminate 1

script:
# Run local charts-testing linting
- docker run --rm -e CHART_DIRS="stable" -v "$(pwd):/workdir" --workdir /workdir gcr.io/kubernetes-charts-ci/chart-testing:${CHART_TESTING_VERSION} chart_test.sh --no-install || travis_terminate 1

# Download kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ || travis_terminate 1
# Scale up GKE cluster

# Wait for Kubernetes to be up and ready.
#- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
# Run remote charts-testing charts install

after_script:
# Scale down GKE cluster

notifications:
  email: false
